stages:
  - build

default:
  tags: [ubuntu22.04]

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  - docker buildx create --use
  - export DOCKER_BUILDKIT=1
  - export POSTGRESQL_VERSION=15
  - export COMPOSER_VERSION=2.6.5
  - export NODE_VERSION=18

build:image:8.2:
  stage: build
  script:
    - export PHP_VERSION=8.2
    - docker buildx build --push --platform linux/amd64 "$PHP_VERSION/" -f "$PHP_VERSION/Dockerfile" --no-cache --pull --build-arg COMPOSER_VERSION --build-arg POSTGRESQL_VERSION -t "$CI_REGISTRY_IMAGE:$PHP_VERSION" -t "$CI_REGISTRY_IMAGE:8" -t "$CI_REGISTRY_IMAGE:latest"
    - docker buildx build --push --platform linux/amd64 "$PHP_VERSION/" -f "$PHP_VERSION/Dockerfile.dev" --no-cache --pull --build-arg "BASE_IMAGE=$CI_REGISTRY_IMAGE:$PHP_VERSION" -t "$CI_REGISTRY_IMAGE:$PHP_VERSION-dev" -t "$CI_REGISTRY_IMAGE:8-dev" -t "$CI_REGISTRY_IMAGE:latest-dev"
    - docker buildx build --push --platform linux/amd64 "$PHP_VERSION/" -f "$PHP_VERSION/Dockerfile.debug" --no-cache --pull --build-arg "BASE_IMAGE=$CI_REGISTRY_IMAGE:$PHP_VERSION-dev" -t "$CI_REGISTRY_IMAGE:$PHP_VERSION-debug" -t "$CI_REGISTRY_IMAGE:8-debug" -t "$CI_REGISTRY_IMAGE:latest-debug"
    - docker buildx build --push --platform linux/amd64 "$PHP_VERSION/" -f "$PHP_VERSION/Dockerfile.fat" --no-cache --pull --build-arg NODE_VERSION --build-arg "BASE_IMAGE=$CI_REGISTRY_IMAGE:$PHP_VERSION" -t "$CI_REGISTRY_IMAGE:$PHP_VERSION-fat" -t "$CI_REGISTRY_IMAGE:8-fat" -t "$CI_REGISTRY_IMAGE:latest-fat"
    - docker buildx build --push --platform linux/amd64 "$PHP_VERSION/" -f "$PHP_VERSION/Dockerfile.dev" --no-cache --pull --build-arg "BASE_IMAGE=$CI_REGISTRY_IMAGE:$PHP_VERSION-fat" -t "$CI_REGISTRY_IMAGE:$PHP_VERSION-fat-dev" -t "$CI_REGISTRY_IMAGE:8-fat-dev" -t "$CI_REGISTRY_IMAGE:latest-fat-dev"
    - docker buildx build --push --platform linux/amd64 "$PHP_VERSION/" -f "$PHP_VERSION/Dockerfile.debug" --no-cache --pull --build-arg "BASE_IMAGE=$CI_REGISTRY_IMAGE:$PHP_VERSION-fat-dev" -t "$CI_REGISTRY_IMAGE:$PHP_VERSION-fat-debug" -t "$CI_REGISTRY_IMAGE:8-fat-debug" -t "$CI_REGISTRY_IMAGE:latest-fat-debug"

build:image:8.1:
  stage: build
  script:
    - export PHP_VERSION=8.1
    - docker buildx build --push --platform linux/amd64 "$PHP_VERSION/" -f "$PHP_VERSION/Dockerfile" --no-cache --pull --build-arg COMPOSER_VERSION --build-arg POSTGRESQL_VERSION -t "$CI_REGISTRY_IMAGE:$PHP_VERSION"
    - docker buildx build --push --platform linux/amd64 "$PHP_VERSION/" -f "$PHP_VERSION/Dockerfile.dev" --no-cache --pull --build-arg "BASE_IMAGE=$CI_REGISTRY_IMAGE:$PHP_VERSION" -t "$CI_REGISTRY_IMAGE:$PHP_VERSION-dev"
    - docker buildx build --push --platform linux/amd64 "$PHP_VERSION/" -f "$PHP_VERSION/Dockerfile.debug" --no-cache --pull --build-arg "BASE_IMAGE=$CI_REGISTRY_IMAGE:$PHP_VERSION-dev" -t "$CI_REGISTRY_IMAGE:$PHP_VERSION-debug"
    - docker buildx build --push --platform linux/amd64 "$PHP_VERSION/" -f "$PHP_VERSION/Dockerfile.fat" --no-cache --pull --build-arg NODE_VERSION --build-arg "BASE_IMAGE=$CI_REGISTRY_IMAGE:$PHP_VERSION" -t "$CI_REGISTRY_IMAGE:$PHP_VERSION-fat"
    - docker buildx build --push --platform linux/amd64 "$PHP_VERSION/" -f "$PHP_VERSION/Dockerfile.dev" --no-cache --pull --build-arg "BASE_IMAGE=$CI_REGISTRY_IMAGE:$PHP_VERSION-fat" -t "$CI_REGISTRY_IMAGE:$PHP_VERSION-fat-dev"
    - docker buildx build --push --platform linux/amd64 "$PHP_VERSION/" -f "$PHP_VERSION/Dockerfile.debug" --no-cache --pull --build-arg "BASE_IMAGE=$CI_REGISTRY_IMAGE:$PHP_VERSION-fat-dev" -t "$CI_REGISTRY_IMAGE:$PHP_VERSION-fat-debug"

build:image:8.0:
  stage: build
  script:
    - export PHP_VERSION=8.0
    - docker buildx build --push --platform linux/amd64 "$PHP_VERSION/" -f "$PHP_VERSION/Dockerfile" --no-cache --pull --build-arg COMPOSER_VERSION --build-arg POSTGRESQL_VERSION -t "$CI_REGISTRY_IMAGE:$PHP_VERSION"
    - docker buildx build --push --platform linux/amd64 "$PHP_VERSION/" -f "$PHP_VERSION/Dockerfile.dev" --no-cache --pull --build-arg "BASE_IMAGE=$CI_REGISTRY_IMAGE:$PHP_VERSION" -t "$CI_REGISTRY_IMAGE:$PHP_VERSION-dev"
    - docker buildx build --push --platform linux/amd64 "$PHP_VERSION/" -f "$PHP_VERSION/Dockerfile.debug" --no-cache --pull --build-arg "BASE_IMAGE=$CI_REGISTRY_IMAGE:$PHP_VERSION-dev" -t "$CI_REGISTRY_IMAGE:$PHP_VERSION-debug"
    - docker buildx build --push --platform linux/amd64 "$PHP_VERSION/" -f "$PHP_VERSION/Dockerfile.fat" --no-cache --pull --build-arg NODE_VERSION --build-arg "BASE_IMAGE=$CI_REGISTRY_IMAGE:$PHP_VERSION" -t "$CI_REGISTRY_IMAGE:$PHP_VERSION-fat"
    - docker buildx build --push --platform linux/amd64 "$PHP_VERSION/" -f "$PHP_VERSION/Dockerfile.dev" --no-cache --pull --build-arg "BASE_IMAGE=$CI_REGISTRY_IMAGE:$PHP_VERSION-fat" -t "$CI_REGISTRY_IMAGE:$PHP_VERSION-fat-dev"
    - docker buildx build --push --platform linux/amd64 "$PHP_VERSION/" -f "$PHP_VERSION/Dockerfile.debug" --no-cache --pull --build-arg "BASE_IMAGE=$CI_REGISTRY_IMAGE:$PHP_VERSION-fat-dev" -t "$CI_REGISTRY_IMAGE:$PHP_VERSION-fat-debug"
